-- DROP TABLES SECTION ---------------------------------------------------

DROP TABLE  IF EXISTS REF_PRODUCT_STATUS
;
DROP TABLE  IF EXISTS REF_PRODUCT
;
DROP TABLE  IF EXISTS REF_BILLING_STATUS
;
DROP TABLE  IF EXISTS TAB_BILLING
;
DROP TABLE  IF EXISTS TAB_ORDERS
;
DROP TABLE  IF EXISTS REF_INVENTORY
;
DROP TABLE  IF EXISTS TAB_METADONNEES
;
DROP TABLE  IF EXISTS TAB_ADDRESS
;
DROP TABLE  IF EXISTS REF_CATEGORY
;
DROP TABLE  IF EXISTS TAB_PRODUCT
;
DROP TABLE  IF EXISTS TAB_PERSON
;

-- DROP SEQUENCES SECTION --------------------------------------------------- 

DROP SEQUENCE IF EXISTS REF_CATEGORY_SEQ
;
DROP SEQUENCE IF EXISTS REF_PRODUCT_STATUS_SEQ
;
DROP SEQUENCE IF EXISTS REF_PRODUCT_SEQ
;
DROP SEQUENCE IF EXISTS TAB_BILLING_SEQ
;
DROP SEQUENCE IF EXISTS TAB_ORDERS_SEQ
;
DROP SEQUENCE IF EXISTS REF_INVENTORY_SEQ
;
DROP SEQUENCE IF EXISTS TAB_PRODUCT_SEQ
;
DROP SEQUENCE IF EXISTS TAB_ADDRESS_SEQ
;
DROP SEQUENCE IF EXISTS TAB_PERSON_SEQ
;
DROP SEQUENCE IF EXISTS TAB_METADONNEES_SEQ
;