SET search_path TO sch_billings;

-- DROP TABLES SECTION ---------------------------------------------------

DELETE FROM TAB_ORDERS
;
DELETE FROM TAB_PRODUCT
;
DELETE FROM TAB_PERSON
;
DELETE FROM TAB_METADONNEES
;
DELETE FROM TAB_ADDRESS
;
DELETE FROM REF_INVENTORY
;
DELETE FROM REF_PRODUCT
;
DELETE FROM REF_PRODUCT_STATUS
;
DELETE FROM REF_BILLING_STATUS
;
DELETE FROM TAB_BILLING
;
DELETE FROM REF_CATEGORY
;
