SET search_path TO sch_billings;

ALTER DEFAULT PRIVILEGES IN SCHEMA sch_billings REVOKE INSERT, SELECT, UPDATE, DELETE ON TABLES FROM user_app CASCADE;
ALTER DEFAULT PRIVILEGES IN SCHEMA sch_billings REVOKE SELECT, UPDATE, USAGE ON SEQUENCES FROM user_app CASCADE;

REVOKE USAGE ON schema sch_billings FROM user_app;
REVOKE CONNECT ON DATABASE bas_billings FROM user_app;

DROP OWNED BY user_app;
DROP ROLE IF EXISTS user_app;